CREATE TABLE `filter_values` (
	`column_name` text,
	`distinct_values_json` text
);
--> statement-breakpoint
CREATE TABLE `products` (
	`Model` text PRIMARY KEY NOT NULL,
	`Product` text,
	`Region` text,
	`Country/Region` text,
	`Machine Type` text,
	`TopSeller` text,
	`Processor` text,
	`Graphics` text,
	`Chipset` text,
	`Memory` text,
	`Memory Slots` text,
	`Max Memory` text,
	`Storage` text,
	`Max Storage Support` text,
	`Storage Slot` text,
	`Card Reader` text,
	`Audio Chip` text,
	`Speakers` text,
	`Camera` text,
	`Microphone` text,
	`Battery` text,
	`Power Adapter` text,
	`Display` text,
	`Touchscreen` text,
	`Keyboard` text,
	`Touchpad` text,
	`Case Color` text,
	`Surface Treatment` text,
	`Case Material` text,
	`Pen` text,
	`Dimensions (WxDxH)` text,
	`Weight` text,
	`Operating System` text,
	`Bundled Software` text,
	`WLAN + Bluetooth` text,
	`WWAN` text,
	`Ethernet` text,
	`NFC` text,
	`Standard Ports` text,
	`Docking` text,
	`Security Chip` text,
	`Fingerprint Reader` text,
	`Base Warranty` text,
	`Included Upgrade` text,
	`Bundled Accessories` text,
	`Green Certifications` text,
	`Other Certifications` text,
	`EAN / UPC / JAN` text,
	`End of Support` text,
	`Announce Date` text,
	`Physical Locks` text,
	`Other Security` text,
	`Optical` text,
	`Screen-to-Body Ratio` text,
	`AI PC Category` text,
	`NPU` text,
	`Color Calibration` text,
	`Mil-Spec Test` text,
	`SIM Card` text,
	`Monitor Cable` text,
	`Optional Ports (configured)` text,
	`Special Features` text,
	`RAID Preset` text,
	`Controls` text,
	`Others` text,
	`System Management` text,
	`Smart Card Reader` text,
	`ISV Certifications` text
);
--> statement-breakpoint
CREATE INDEX `idx_display` ON `products` (`Display`);--> statement-breakpoint
CREATE INDEX `idx_processor` ON `products` (`Processor`);--> statement-breakpoint
CREATE INDEX `idx_memory` ON `products` (`Memory`);--> statement-breakpoint
CREATE INDEX `idx_country_region` ON `products` (`Country/Region`);