import { sqliteTable, index, text } from "drizzle-orm/sqlite-core"
  import { sql } from "drizzle-orm"

export const products = sqliteTable("products", {
	model: text("Model").primaryKey(),
	product: text("Product"),
	region: text("Region"),
	"country/region": text("Country/Region"),
	machineType: text("Machine Type"),
	topSeller: text("TopSeller"),
	processor: text("Processor"),
	graphics: text("Graphics"),
	chipset: text("Chipset"),
	memory: text("Memory"),
	memorySlots: text("Memory Slots"),
	maxMemory: text("Max Memory"),
	storage: text("Storage"),
	maxStorageSupport: text("Max Storage Support"),
	storageSlot: text("Storage Slot"),
	cardReader: text("Card Reader"),
	audioChip: text("Audio Chip"),
	speakers: text("Speakers"),
	camera: text("Camera"),
	microphone: text("Microphone"),
	battery: text("Battery"),
	powerAdapter: text("Power Adapter"),
	display: text("Display"),
	touchscreen: text("Touchscreen"),
	keyboard: text("Keyboard"),
	touchpad: text("Touchpad"),
	caseColor: text("Case Color"),
	surfaceTreatment: text("Surface Treatment"),
	caseMaterial: text("Case Material"),
	pen: text("Pen"),
	"dimensions (wxDxH)": text("Dimensions (WxDxH)"),
	weight: text("Weight"),
	operatingSystem: text("Operating System"),
	bundledSoftware: text("Bundled Software"),
	"wlan +Bluetooth": text("WLAN + Bluetooth"),
	wwan: text("WWAN"),
	ethernet: text("Ethernet"),
	nfc: text("NFC"),
	standardPorts: text("Standard Ports"),
	docking: text("Docking"),
	securityChip: text("Security Chip"),
	fingerprintReader: text("Fingerprint Reader"),
	baseWarranty: text("Base Warranty"),
	includedUpgrade: text("Included Upgrade"),
	bundledAccessories: text("Bundled Accessories"),
	greenCertifications: text("Green Certifications"),
	otherCertifications: text("Other Certifications"),
	"ean /Upc /Jan": text("EAN / UPC / JAN"),
	endOfSupport: text("End of Support"),
	announceDate: text("Announce Date"),
	physicalLocks: text("Physical Locks"),
	otherSecurity: text("Other Security"),
	optical: text("Optical"),
	screenToBodyRatio: text("Screen-to-Body Ratio"),
	aiPcCategory: text("AI PC Category"),
	npu: text("NPU"),
	colorCalibration: text("Color Calibration"),
	milSpecTest: text("Mil-Spec Test"),
	simCard: text("SIM Card"),
	monitorCable: text("Monitor Cable"),
	"optionalPorts (configured)": text("Optional Ports (configured)"),
	specialFeatures: text("Special Features"),
	raidPreset: text("RAID Preset"),
	controls: text("Controls"),
	others: text("Others"),
	systemManagement: text("System Management"),
	smartCardReader: text("Smart Card Reader"),
	isvCertifications: text("ISV Certifications"),
},
(table) => [
	index("idx_display").on(table.display),
	index("idx_processor").on(table.processor),
	index("idx_memory").on(table.memory),
	index("idx_country_region").on(table["country/region"]),
]);

export const filterValues = sqliteTable("filter_values", {
	columnName: text("column_name"),
	distinctValuesJson: text("distinct_values_json"),
});
