import type { ColumnDef } from "@tanstack/table-core";

export const columns = [
  { header: 'Product', accessorKey: 'product', maxSize: 200 },
  { header: 'Region', accessorKey: 'region' },
  { header: 'Country/Region', accessorKey: "country/region" },
  { header: 'Machine Type', accessorKey: 'machineType' },
  { header: 'Processor', accessorKey: 'processor' },
  { header: 'Graphics', accessorKey: 'graphics' },
  { header: 'Chipset', accessorKey: 'chipset' },
  { header: 'Memory', accessorKey: 'memory' },
  { header: 'Memory Slots', accessorKey: 'memorySlots' },
  { header: 'Max Memory', accessorKey: 'maxMemory' },
  { header: 'Storage', accessorKey: 'storage' },
  { header: 'Max Storage Support', accessorKey: 'maxStorageSupport' },
  { header: 'Storage Slot', accessorKey: 'storageSlot' },
  { header: 'Card Reader', accessorKey: 'cardReader' },
  { header: 'Audio Chip', accessorKey: 'audioChip' },
  { header: 'Speakers', accessorKey: 'speakers' },
  { header: 'Camera', accessorKey: 'camera' },
  { header: 'Microphone', accessorKey: 'microphone' },
  { header: 'Battery', accessorKey: 'battery' },
  { header: 'Power Adapter', accessorKey: 'powerAdapter' },
  { header: 'Display', accessorKey: 'display' },
  { header: 'Touchscreen', accessorKey: 'touchscreen' },
  { header: 'Keyboard', accessorKey: 'keyboard' },
  { header: 'Touchpad', accessorKey: 'touchpad' },
  { header: 'Case Color', accessorKey: 'caseColor' },
  { header: 'Surface Treatment', accessorKey: 'surfaceTreatment' },
  { header: 'Case Material', accessorKey: 'caseMaterial' },
  { header: 'Pen', accessorKey: 'pen' },
  { header: 'Dimensions (WxDxH)', accessorKey: "dimensions (wxDxH)" },
  { header: 'Weight', accessorKey: 'weight' },
  { header: 'Operating System', accessorKey: 'operatingSystem' },
  { header: 'Bundled Software', accessorKey: 'bundledSoftware' },
  { header: 'WLAN + Bluetooth', accessorKey: 'wlanBluetooth' },
  { header: 'WWAN', accessorKey: 'wwan' },
  { header: 'Ethernet', accessorKey: 'ethernet' },
  { header: 'NFC', accessorKey: 'nfc' },
  { header: 'Standard Ports', accessorKey: 'standardPorts' },
  { header: 'Docking', accessorKey: 'docking' },
  { header: 'Security Chip', accessorKey: 'securityChip' },
  { header: 'Fingerprint Reader', accessorKey: 'fingerprintReader' },
  { header: 'Base Warranty', accessorKey: 'baseWarranty' },
  { header: 'Included Upgrade', accessorKey: 'includedUpgrade' },
  { header: 'Bundled Accessories', accessorKey: 'bundledAccessories' },
  { header: 'Green Certifications', accessorKey: 'greenCertifications' },
  { header: 'Other Certifications', accessorKey: 'otherCertifications' },
  { header: 'EAN / UPC / JAN', accessorKey: 'eanUpcJan' },
  { header: 'End of Support', accessorKey: 'endOfSupport' },
  { header: 'Announce Date', accessorKey: 'announceDate' },
  { header: 'Physical Locks', accessorKey: 'physicalLocks' },
  { header: 'Other Security', accessorKey: 'otherSecurity' },
  { header: 'Optical', accessorKey: 'optical' },
  { header: 'Screen-to-Body Ratio', accessorKey: 'screen-to-bodyRatio' },
  { header: 'AI PC Category', accessorKey: 'aiPcCategory' },
  { header: 'NPU', accessorKey: 'npu' },
  { header: 'Color Calibration', accessorKey: 'colorCalibration' },
  { header: 'Mil-Spec Test', accessorKey: 'mil-specTest' },
  { header: 'SIM Card', accessorKey: 'simCard' },
  { header: 'Optional Ports (configured)', accessorKey: 'optionalPortsConfigured' },
  { header: 'Special Features', accessorKey: 'specialFeatures' },
  { header: 'RAID Preset', accessorKey: 'raidPreset' },
  { header: 'System Management', accessorKey: 'systemManagement' },
  { header: 'Smart Card Reader', accessorKey: 'smartCardReader' },
] as const satisfies ColumnDef<{}, string>[];
